// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Domain.Entities;
using Microsoft.EntityFrameworkCore;

namespace Infrastructure.Persistence;

public partial class SmootieerpDbConText : DbContext
{
    public SmootieerpDbConText(DbContextOptions<SmootieerpDbConText> options)
        : base(options)
    {
    }

    public virtual DbSet<AttendanceLog> AttendanceLogs { get; set; }

    public virtual DbSet<Branch> Branches { get; set; }

    public virtual DbSet<CounterStock> CounterStocks { get; set; }

    public virtual DbSet<Coupon> Coupons { get; set; }

    public virtual DbSet<Customer> Customers { get; set; }

    public virtual DbSet<CustomerCoupon> CustomerCoupons { get; set; }

    public virtual DbSet<CustomerPoint> CustomerPoints { get; set; }

    public virtual DbSet<Employee> Employees { get; set; }

    public virtual DbSet<EmployeeShift> EmployeeShifts { get; set; }

    public virtual DbSet<Ingredient> Ingredients { get; set; }

    public virtual DbSet<Menu> Menus { get; set; }

    public virtual DbSet<MenuCategory> MenuCategories { get; set; }

    public virtual DbSet<MenuRecipe> MenuRecipes { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<OrderItem> OrderItems { get; set; }

    public virtual DbSet<Referral> Referrals { get; set; }

    public virtual DbSet<Refreshtoken> Refreshtokens { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<Shift> Shifts { get; set; }

    public virtual DbSet<StockItem> StockItems { get; set; }

    public virtual DbSet<StockRequest> StockRequests { get; set; }

    public virtual DbSet<StockRequestItem> StockRequestItems { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .UseCollation("utf8mb4_general_ci")
            .HasCharSet("utf8mb4");

        modelBuilder.Entity<AttendanceLog>(entity =>
        {
            entity.HasKey(e => e.LogId).HasName("PRIMARY");

            entity.ToTable("attendance_logs");

            entity.HasIndex(e => e.EmployeeId, "employee_id");

            entity.HasIndex(e => e.ShiftId, "shift_id");

            entity.Property(e => e.LogId)
                .HasColumnType("int(11)")
                .HasColumnName("log_id");
            entity.Property(e => e.CheckInTime)
                .HasColumnType("datetime")
                .HasColumnName("check_in_time");
            entity.Property(e => e.CheckOutTime)
                .HasColumnType("datetime")
                .HasColumnName("check_out_time");
            entity.Property(e => e.EmployeeId)
                .HasColumnType("int(11)")
                .HasColumnName("employee_id");
            entity.Property(e => e.ShiftId)
                .HasColumnType("int(11)")
                .HasColumnName("shift_id");
            entity.Property(e => e.WorkDate).HasColumnName("work_date");

            entity.HasOne(d => d.Employee).WithMany(p => p.AttendanceLogs)
                .HasForeignKey(d => d.EmployeeId)
                .HasConstraintName("attendance_logs_ibfk_1");

            entity.HasOne(d => d.Shift).WithMany(p => p.AttendanceLogs)
                .HasForeignKey(d => d.ShiftId)
                .HasConstraintName("attendance_logs_ibfk_2");
        });

        modelBuilder.Entity<Branch>(entity =>
        {
            entity.HasKey(e => e.BranchId).HasName("PRIMARY");

            entity.ToTable("branches");

            entity.Property(e => e.BranchId)
                .HasColumnType("int(11)")
                .HasColumnName("branch_id");
            entity.Property(e => e.AddressDetail)
                .HasColumnType("text")
                .HasColumnName("address_detail");
            entity.Property(e => e.BranchName)
                .HasMaxLength(100)
                .HasColumnName("branch_name");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(50)
                .HasColumnName("created_by");
            entity.Property(e => e.CreatedDate)
                .HasColumnType("datetime")
                .HasColumnName("created_date");
            entity.Property(e => e.District)
                .HasMaxLength(100)
                .HasColumnName("district");
            entity.Property(e => e.IsUsed)
                .HasDefaultValueSql("'1'")
                .HasColumnName("is_used");
            entity.Property(e => e.PostalCode)
                .HasMaxLength(10)
                .HasColumnName("postal_code");
            entity.Property(e => e.Province)
                .HasMaxLength(100)
                .HasColumnName("province");
            entity.Property(e => e.SubDistrict)
                .HasMaxLength(100)
                .HasColumnName("sub_district");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(50)
                .HasColumnName("updated_by");
            entity.Property(e => e.UpdatedDate)
                .HasColumnType("datetime")
                .HasColumnName("updated_date");
        });

        modelBuilder.Entity<CounterStock>(entity =>
        {
            entity.HasKey(e => e.CounterStockId).HasName("PRIMARY");

            entity.ToTable("counter_stocks");

            entity.HasIndex(e => e.BranchId, "branch_id");

            entity.HasIndex(e => e.IngredientId, "ingredient_id");

            entity.Property(e => e.CounterStockId)
                .HasColumnType("int(11)")
                .HasColumnName("counter_stock_id");
            entity.Property(e => e.BranchId)
                .HasColumnType("int(11)")
                .HasColumnName("branch_id");
            entity.Property(e => e.IngredientId)
                .HasColumnType("int(11)")
                .HasColumnName("ingredient_id");
            entity.Property(e => e.LastUpdated)
                .HasDefaultValueSql("current_timestamp()")
                .HasColumnType("datetime")
                .HasColumnName("last_updated");
            entity.Property(e => e.Quantity)
                .HasColumnType("int(11)")
                .HasColumnName("quantity");

            entity.HasOne(d => d.Branch).WithMany(p => p.CounterStocks)
                .HasForeignKey(d => d.BranchId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("counter_stocks_ibfk_1");

            entity.HasOne(d => d.Ingredient).WithMany(p => p.CounterStocks)
                .HasForeignKey(d => d.IngredientId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("counter_stocks_ibfk_2");
        });

        modelBuilder.Entity<Coupon>(entity =>
        {
            entity.HasKey(e => e.CouponId).HasName("PRIMARY");

            entity.ToTable("coupons");

            entity.HasIndex(e => e.Code, "code").IsUnique();

            entity.Property(e => e.CouponId)
                .HasColumnType("int(11)")
                .HasColumnName("coupon_id");
            entity.Property(e => e.Code)
                .HasMaxLength(50)
                .HasColumnName("code");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(50)
                .HasColumnName("created_by");
            entity.Property(e => e.CreatedDate)
                .HasColumnType("datetime")
                .HasColumnName("created_date");
            entity.Property(e => e.Description)
                .HasColumnType("text")
                .HasColumnName("description");
            entity.Property(e => e.DiscountType)
                .HasMaxLength(50)
                .HasColumnName("discount_type");
            entity.Property(e => e.DiscountValue)
                .HasPrecision(10, 2)
                .HasColumnName("discount_value");
            entity.Property(e => e.ExpiryDate)
                .HasColumnType("datetime")
                .HasColumnName("expiry_date");
            entity.Property(e => e.IsUsed)
                .HasDefaultValueSql("'1'")
                .HasColumnName("is_used");
            entity.Property(e => e.MinimumCount)
                .HasColumnType("int(11)")
                .HasColumnName("minimum_count");
            entity.Property(e => e.MinimumPurchase)
                .HasPrecision(10, 2)
                .HasColumnName("minimum_purchase");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(50)
                .HasColumnName("updated_by");
            entity.Property(e => e.UpdatedDate)
                .HasColumnType("datetime")
                .HasColumnName("updated_date");
        });

        modelBuilder.Entity<Customer>(entity =>
        {
            entity.HasKey(e => e.CustomerId).HasName("PRIMARY");

            entity.ToTable("customers");

            entity.Property(e => e.CustomerId)
                .ValueGeneratedNever()
                .HasColumnType("int(11)")
                .HasColumnName("customer_id");
            entity.Property(e => e.Birthdate).HasColumnName("birthdate");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(50)
                .HasColumnName("created_by");
            entity.Property(e => e.CreatedDate)
                .HasColumnType("datetime")
                .HasColumnName("created_date");
            entity.Property(e => e.Email)
                .HasMaxLength(100)
                .HasColumnName("email");
            entity.Property(e => e.Fullname)
                .HasMaxLength(100)
                .HasColumnName("fullname");
            entity.Property(e => e.IsUsed)
                .HasDefaultValueSql("'1'")
                .HasColumnName("is_used");
            entity.Property(e => e.Password)
                .HasMaxLength(255)
                .HasColumnName("password");
            entity.Property(e => e.Phone)
                .HasMaxLength(20)
                .HasColumnName("phone");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(50)
                .HasColumnName("updated_by");
            entity.Property(e => e.UpdatedDate)
                .HasColumnType("datetime")
                .HasColumnName("updated_date");
        });

        modelBuilder.Entity<CustomerCoupon>(entity =>
        {
            entity.HasKey(e => new { e.CustomerId, e.CouponId })
                .HasName("PRIMARY")
                .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

            entity.ToTable("customer_coupons");

            entity.HasIndex(e => e.CouponId, "coupon_id");

            entity.Property(e => e.CustomerId)
                .HasColumnType("int(11)")
                .HasColumnName("customer_id");
            entity.Property(e => e.CouponId)
                .HasColumnType("int(11)")
                .HasColumnName("coupon_id");
            entity.Property(e => e.AssignedDate)
                .HasDefaultValueSql("current_timestamp()")
                .HasColumnType("datetime")
                .HasColumnName("assigned_date");
            entity.Property(e => e.IsUsed)
                .HasDefaultValueSql("'0'")
                .HasColumnName("is_used");
            entity.Property(e => e.UsedDate)
                .HasColumnType("datetime")
                .HasColumnName("used_date");

            entity.HasOne(d => d.Coupon).WithMany(p => p.CustomerCoupons)
                .HasForeignKey(d => d.CouponId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("customer_coupons_ibfk_2");

            entity.HasOne(d => d.Customer).WithMany(p => p.CustomerCoupons)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("customer_coupons_ibfk_1");
        });

        modelBuilder.Entity<CustomerPoint>(entity =>
        {
            entity.HasKey(e => e.CustomerId).HasName("PRIMARY");

            entity.ToTable("customer_points");

            entity.Property(e => e.CustomerId)
                .ValueGeneratedNever()
                .HasColumnType("int(11)")
                .HasColumnName("customer_id");
            entity.Property(e => e.LastUpdated)
                .HasColumnType("datetime")
                .HasColumnName("last_updated");
            entity.Property(e => e.TotalPoints)
                .HasDefaultValueSql("'0'")
                .HasColumnType("int(11)")
                .HasColumnName("total_points");

            entity.HasOne(d => d.Customer).WithOne(p => p.CustomerPoint)
                .HasForeignKey<CustomerPoint>(d => d.CustomerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("customer_points_ibfk_1");
        });

        modelBuilder.Entity<Employee>(entity =>
        {
            entity.HasKey(e => e.EmployeeId).HasName("PRIMARY");

            entity.ToTable("employees");

            entity.HasIndex(e => e.BranchId, "branch_id");

            entity.HasIndex(e => e.RoleId, "role_id");

            entity.Property(e => e.EmployeeId)
                .HasColumnType("int(11)")
                .HasColumnName("employee_id");
            entity.Property(e => e.BranchId)
                .HasColumnType("int(11)")
                .HasColumnName("branch_id");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(50)
                .HasColumnName("created_by");
            entity.Property(e => e.CreatedDate)
                .HasColumnType("datetime")
                .HasColumnName("created_date");
            entity.Property(e => e.Email)
                .HasMaxLength(100)
                .HasColumnName("email");
            entity.Property(e => e.Fullname)
                .HasMaxLength(100)
                .HasColumnName("fullname");
            entity.Property(e => e.HireDate)
                .HasColumnType("datetime")
                .HasColumnName("hire_date");
            entity.Property(e => e.Image)
                .HasColumnType("text")
                .HasColumnName("image");
            entity.Property(e => e.IsUsed)
                .HasDefaultValueSql("'1'")
                .HasColumnName("is_used");
            entity.Property(e => e.PasswordHash)
                .HasMaxLength(255)
                .HasColumnName("password_hash");
            entity.Property(e => e.PhoneNumber)
                .HasMaxLength(20)
                .HasColumnName("phone_number");
            entity.Property(e => e.RoleId)
                .HasColumnType("int(11)")
                .HasColumnName("role_id");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasColumnName("status");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(50)
                .HasColumnName("updated_by");
            entity.Property(e => e.UpdatedDate)
                .HasColumnType("datetime")
                .HasColumnName("updated_date");

            entity.HasOne(d => d.Branch).WithMany(p => p.Employees)
                .HasForeignKey(d => d.BranchId)
                .HasConstraintName("employees_ibfk_1");

            entity.HasOne(d => d.Role).WithMany(p => p.Employees)
                .HasForeignKey(d => d.RoleId)
                .HasConstraintName("employees_ibfk_2");
        });

        modelBuilder.Entity<EmployeeShift>(entity =>
        {
            entity.HasKey(e => e.Esid).HasName("PRIMARY");

            entity.ToTable("employee_shifts");

            entity.HasIndex(e => e.EmployeeId, "employee_id");

            entity.HasIndex(e => e.ShiftId, "shift_id");

            entity.Property(e => e.Esid)
                .HasColumnType("int(11)")
                .HasColumnName("esid");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(50)
                .HasColumnName("created_by");
            entity.Property(e => e.CreatedDate)
                .HasColumnType("datetime")
                .HasColumnName("created_date");
            entity.Property(e => e.EmployeeId)
                .HasColumnType("int(11)")
                .HasColumnName("employee_id");
            entity.Property(e => e.IsUsed)
                .HasDefaultValueSql("'1'")
                .HasColumnName("is_used");
            entity.Property(e => e.ShiftId)
                .HasColumnType("int(11)")
                .HasColumnName("shift_id");
            entity.Property(e => e.UpdateDate)
                .HasColumnType("datetime")
                .HasColumnName("update_date");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(50)
                .HasColumnName("updated_by");

            entity.HasOne(d => d.Employee).WithMany(p => p.EmployeeShifts)
                .HasForeignKey(d => d.EmployeeId)
                .HasConstraintName("employee_shifts_ibfk_1");

            entity.HasOne(d => d.Shift).WithMany(p => p.EmployeeShifts)
                .HasForeignKey(d => d.ShiftId)
                .HasConstraintName("employee_shifts_ibfk_2");
        });

        modelBuilder.Entity<Ingredient>(entity =>
        {
            entity.HasKey(e => e.IngredientId).HasName("PRIMARY");

            entity.ToTable("ingredients");

            entity.HasIndex(e => e.Name, "name").IsUnique();

            entity.Property(e => e.IngredientId)
                .HasColumnType("int(11)")
                .HasColumnName("ingredient_id");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(50)
                .HasColumnName("created_by");
            entity.Property(e => e.CreatedDate)
                .HasColumnType("datetime")
                .HasColumnName("created_date");
            entity.Property(e => e.IsUsed)
                .HasDefaultValueSql("'1'")
                .HasColumnName("is_used");
            entity.Property(e => e.Name)
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.Unit).HasMaxLength(100);
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(50)
                .HasColumnName("updated_by");
            entity.Property(e => e.UpdatedDate)
                .HasColumnType("datetime")
                .HasColumnName("updated_date");
        });

        modelBuilder.Entity<Menu>(entity =>
        {
            entity.HasKey(e => e.MenuId).HasName("PRIMARY");

            entity.ToTable("menus");

            entity.HasIndex(e => e.CategoryId, "category_id");

            entity.Property(e => e.MenuId)
                .HasColumnType("int(11)")
                .HasColumnName("menu_id");
            entity.Property(e => e.CategoryId)
                .HasColumnType("int(11)")
                .HasColumnName("category_id");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(50)
                .HasColumnName("created_by");
            entity.Property(e => e.CreatedDate)
                .HasColumnType("datetime")
                .HasColumnName("created_date");
            entity.Property(e => e.Image)
                .HasColumnType("text")
                .HasColumnName("image");
            entity.Property(e => e.IsUsed)
                .HasDefaultValueSql("'1'")
                .HasColumnName("is_used");
            entity.Property(e => e.Name)
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.Price)
                .HasPrecision(10, 2)
                .HasColumnName("price");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(50)
                .HasColumnName("updated_by");
            entity.Property(e => e.UpdatedDate)
                .HasColumnType("datetime")
                .HasColumnName("updated_date");

            entity.HasOne(d => d.Category).WithMany(p => p.Menus)
                .HasForeignKey(d => d.CategoryId)
                .HasConstraintName("menus_ibfk_1");
        });

        modelBuilder.Entity<MenuCategory>(entity =>
        {
            entity.HasKey(e => e.CategoryId).HasName("PRIMARY");

            entity.ToTable("menu_categories");

            entity.Property(e => e.CategoryId)
                .HasColumnType("int(11)")
                .HasColumnName("category_id");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(50)
                .HasColumnName("created_by");
            entity.Property(e => e.CreatedDate)
                .HasColumnType("datetime")
                .HasColumnName("created_date");
            entity.Property(e => e.Description)
                .HasColumnType("text")
                .HasColumnName("description");
            entity.Property(e => e.IsUsed)
                .HasDefaultValueSql("'1'")
                .HasColumnName("is_used");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(50)
                .HasColumnName("updated_by");
            entity.Property(e => e.UpdatedDate)
                .HasColumnType("datetime")
                .HasColumnName("updated_date");
        });

        modelBuilder.Entity<MenuRecipe>(entity =>
        {
            entity.HasKey(e => e.RecipeId).HasName("PRIMARY");

            entity.ToTable("menu_recipes");

            entity.HasIndex(e => e.IngredientId, "ingredient_id");

            entity.HasIndex(e => e.MenuId, "menu_id");

            entity.Property(e => e.RecipeId)
                .HasColumnType("int(11)")
                .HasColumnName("recipe_id");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(50)
                .HasColumnName("created_by");
            entity.Property(e => e.CreatedDate)
                .HasColumnType("datetime")
                .HasColumnName("created_date");
            entity.Property(e => e.IngredientId)
                .HasColumnType("int(11)")
                .HasColumnName("ingredient_id");
            entity.Property(e => e.MenuId)
                .HasColumnType("int(11)")
                .HasColumnName("menu_id");
            entity.Property(e => e.Quantity)
                .HasPrecision(10, 2)
                .HasColumnName("quantity");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(50)
                .HasColumnName("updated_by");
            entity.Property(e => e.UpdatedDate)
                .HasColumnType("datetime")
                .HasColumnName("updated_date");

            entity.HasOne(d => d.Ingredient).WithMany(p => p.MenuRecipes)
                .HasForeignKey(d => d.IngredientId)
                .HasConstraintName("menu_recipes_ibfk_2");

            entity.HasOne(d => d.Menu).WithMany(p => p.MenuRecipes)
                .HasForeignKey(d => d.MenuId)
                .HasConstraintName("menu_recipes_ibfk_1");
        });

        modelBuilder.Entity<Order>(entity =>
        {
            entity.HasKey(e => e.OrderId).HasName("PRIMARY");

            entity.ToTable("orders");

            entity.HasIndex(e => e.BranchId, "branch_id");

            entity.HasIndex(e => e.CouponId, "coupon_id");

            entity.HasIndex(e => e.CustomerId, "customer_id");

            entity.Property(e => e.OrderId)
                .HasColumnType("int(11)")
                .HasColumnName("order_id");
            entity.Property(e => e.BranchId)
                .HasColumnType("int(11)")
                .HasColumnName("branch_id");
            entity.Property(e => e.Channel)
                .HasMaxLength(50)
                .HasColumnName("channel");
            entity.Property(e => e.CouponId)
                .HasColumnType("int(11)")
                .HasColumnName("coupon_id");
            entity.Property(e => e.CustomerId)
                .HasColumnType("int(11)")
                .HasColumnName("customer_id");
            entity.Property(e => e.DeliveryStatus)
                .HasMaxLength(50)
                .HasColumnName("delivery_status");
            entity.Property(e => e.DiscountAmount)
                .HasPrecision(10, 2)
                .HasDefaultValueSql("'0.00'")
                .HasColumnName("discount_amount");
            entity.Property(e => e.FinalAmount)
                .HasPrecision(10, 2)
                .HasColumnName("final_amount");
            entity.Property(e => e.OrderTime)
                .HasColumnType("datetime")
                .HasColumnName("order_time");
            entity.Property(e => e.PaymentMethod)
                .HasMaxLength(50)
                .HasColumnName("payment_method");
            entity.Property(e => e.PickupMethod)
                .HasMaxLength(50)
                .HasColumnName("pickup_method");
            entity.Property(e => e.PickupTime)
                .HasColumnType("datetime")
                .HasColumnName("pickup_time");
            entity.Property(e => e.PointsEarned)
                .HasDefaultValueSql("'0'")
                .HasColumnType("int(11)")
                .HasColumnName("points_earned");
            entity.Property(e => e.PointsUsed)
                .HasDefaultValueSql("'0'")
                .HasColumnType("int(11)")
                .HasColumnName("points_used");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasColumnName("status");
            entity.Property(e => e.TotalAmount)
                .HasPrecision(10, 2)
                .HasColumnName("total_amount");

            entity.HasOne(d => d.Branch).WithMany(p => p.Orders)
                .HasForeignKey(d => d.BranchId)
                .HasConstraintName("orders_ibfk_3");

            entity.HasOne(d => d.Coupon).WithMany(p => p.Orders)
                .HasForeignKey(d => d.CouponId)
                .HasConstraintName("orders_ibfk_4");

            entity.HasOne(d => d.Customer).WithMany(p => p.Orders)
                .HasForeignKey(d => d.CustomerId)
                .HasConstraintName("orders_ibfk_1");
        });

        modelBuilder.Entity<OrderItem>(entity =>
        {
            entity.HasKey(e => e.OrderItemId).HasName("PRIMARY");

            entity.ToTable("order_items");

            entity.HasIndex(e => e.MenuId, "menu_id");

            entity.HasIndex(e => e.OrderId, "order_id");

            entity.Property(e => e.OrderItemId)
                .HasColumnType("int(11)")
                .HasColumnName("order_item_id");
            entity.Property(e => e.MenuId)
                .HasColumnType("int(11)")
                .HasColumnName("menu_id");
            entity.Property(e => e.OrderId)
                .HasColumnType("int(11)")
                .HasColumnName("order_id");
            entity.Property(e => e.Price)
                .HasPrecision(10, 2)
                .HasColumnName("price");
            entity.Property(e => e.Quantity)
                .HasColumnType("int(11)")
                .HasColumnName("quantity");

            entity.HasOne(d => d.Menu).WithMany(p => p.OrderItems)
                .HasForeignKey(d => d.MenuId)
                .HasConstraintName("order_items_ibfk_2");

            entity.HasOne(d => d.Order).WithMany(p => p.OrderItems)
                .HasForeignKey(d => d.OrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("order_items_ibfk_1");
        });

        modelBuilder.Entity<Referral>(entity =>
        {
            entity.HasKey(e => e.ReferralId).HasName("PRIMARY");

            entity.ToTable("referrals");

            entity.HasIndex(e => e.ReferredId, "referred_id");

            entity.HasIndex(e => e.ReferrerId, "referrer_id");

            entity.Property(e => e.ReferralId)
                .HasColumnType("int(11)")
                .HasColumnName("referral_id");
            entity.Property(e => e.ReferredDate)
                .HasColumnType("datetime")
                .HasColumnName("referred_date");
            entity.Property(e => e.ReferredId)
                .HasColumnType("int(11)")
                .HasColumnName("referred_id");
            entity.Property(e => e.ReferrerId)
                .HasColumnType("int(11)")
                .HasColumnName("referrer_id");
            entity.Property(e => e.RewardGiven)
                .HasDefaultValueSql("'0'")
                .HasColumnName("reward_given");

            entity.HasOne(d => d.Referred).WithMany(p => p.ReferralReferreds)
                .HasForeignKey(d => d.ReferredId)
                .HasConstraintName("referrals_ibfk_2");

            entity.HasOne(d => d.Referrer).WithMany(p => p.ReferralReferrers)
                .HasForeignKey(d => d.ReferrerId)
                .HasConstraintName("referrals_ibfk_1");
        });

        modelBuilder.Entity<Refreshtoken>(entity =>
        {
            entity.HasKey(e => e.Rfid).HasName("PRIMARY");

            entity.ToTable("refreshtoken");

            entity.Property(e => e.Rfid)
                .HasColumnType("int(11)")
                .HasColumnName("RFID");
            entity.Property(e => e.ExpiresAt).HasColumnType("datetime");
            entity.Property(e => e.JwtTokenId)
                .IsRequired()
                .HasColumnType("text");
            entity.Property(e => e.RefreshToken)
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("Refresh_Token");
            entity.Property(e => e.UserId).HasColumnType("int(11)");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("PRIMARY");

            entity.ToTable("roles");

            entity.Property(e => e.RoleId)
                .HasColumnType("int(11)")
                .HasColumnName("role_id");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(50)
                .HasColumnName("created_by");
            entity.Property(e => e.CreatedDate)
                .HasColumnType("datetime")
                .HasColumnName("created_date");
            entity.Property(e => e.IsUsed)
                .HasDefaultValueSql("'1'")
                .HasColumnName("is_used");
            entity.Property(e => e.RoleName)
                .HasMaxLength(50)
                .HasColumnName("role_name");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(50)
                .HasColumnName("updated_by");
            entity.Property(e => e.UpdatedDate)
                .HasColumnType("datetime")
                .HasColumnName("updated_date");
        });

        modelBuilder.Entity<Shift>(entity =>
        {
            entity.HasKey(e => e.ShiftId).HasName("PRIMARY");

            entity.ToTable("shifts");

            entity.HasIndex(e => e.BranchId, "branch_id");

            entity.Property(e => e.ShiftId)
                .HasColumnType("int(11)")
                .HasColumnName("shift_id");
            entity.Property(e => e.BranchId)
                .HasColumnType("int(11)")
                .HasColumnName("branch_id");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(50)
                .HasColumnName("created_by");
            entity.Property(e => e.CreatedDate)
                .HasColumnType("datetime")
                .HasColumnName("created_date");
            entity.Property(e => e.EndTime)
                .HasColumnType("time")
                .HasColumnName("end_time");
            entity.Property(e => e.IsUsed)
                .HasDefaultValueSql("'1'")
                .HasColumnName("is_used");
            entity.Property(e => e.ShiftName)
                .HasMaxLength(50)
                .HasColumnName("shift_name");
            entity.Property(e => e.StartTime)
                .HasColumnType("time")
                .HasColumnName("start_time");
            entity.Property(e => e.UpdateDate)
                .HasColumnType("datetime")
                .HasColumnName("update_date");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(50)
                .HasColumnName("updated_by");

            entity.HasOne(d => d.Branch).WithMany(p => p.Shifts)
                .HasForeignKey(d => d.BranchId)
                .HasConstraintName("shifts_ibfk_1");
        });

        modelBuilder.Entity<StockItem>(entity =>
        {
            entity.HasKey(e => e.StockId).HasName("PRIMARY");

            entity.ToTable("stock_items");

            entity.HasIndex(e => e.BranchId, "branch_id");

            entity.HasIndex(e => e.IngredientId, "ingredient_id");

            entity.Property(e => e.StockId)
                .HasColumnType("int(11)")
                .HasColumnName("stock_id");
            entity.Property(e => e.BranchId)
                .HasColumnType("int(11)")
                .HasColumnName("branch_id");
            entity.Property(e => e.CreatedDate)
                .HasColumnType("datetime")
                .HasColumnName("created_date");
            entity.Property(e => e.IngredientId)
                .HasColumnType("int(11)")
                .HasColumnName("ingredient_id");
            entity.Property(e => e.Quantity)
                .HasPrecision(10, 2)
                .HasColumnName("quantity");

            entity.HasOne(d => d.Branch).WithMany(p => p.StockItems)
                .HasForeignKey(d => d.BranchId)
                .HasConstraintName("stock_items_ibfk_1");

            entity.HasOne(d => d.Ingredient).WithMany(p => p.StockItems)
                .HasForeignKey(d => d.IngredientId)
                .HasConstraintName("stock_items_ibfk_2");
        });

        modelBuilder.Entity<StockRequest>(entity =>
        {
            entity.HasKey(e => e.RequestId).HasName("PRIMARY");

            entity.ToTable("stock_requests");

            entity.HasIndex(e => e.BranchId, "branch_id");

            entity.HasIndex(e => e.EmployeeId, "employee_id");

            entity.Property(e => e.RequestId)
                .HasColumnType("int(11)")
                .HasColumnName("request_id");
            entity.Property(e => e.ApprovedBy)
                .HasMaxLength(50)
                .HasColumnName("approved_by");
            entity.Property(e => e.ApprovedDate)
                .HasColumnType("datetime")
                .HasColumnName("approved_date");
            entity.Property(e => e.BranchId)
                .HasColumnType("int(11)")
                .HasColumnName("branch_id");
            entity.Property(e => e.EmployeeId)
                .HasColumnType("int(11)")
                .HasColumnName("employee_id");
            entity.Property(e => e.RequestDate)
                .HasColumnType("datetime")
                .HasColumnName("request_date");
            entity.Property(e => e.RequestType)
                .HasMaxLength(50)
                .HasColumnName("request_type");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasColumnName("status");

            entity.HasOne(d => d.Branch).WithMany(p => p.StockRequests)
                .HasForeignKey(d => d.BranchId)
                .HasConstraintName("stock_requests_ibfk_2");

            entity.HasOne(d => d.Employee).WithMany(p => p.StockRequests)
                .HasForeignKey(d => d.EmployeeId)
                .HasConstraintName("stock_requests_ibfk_1");
        });

        modelBuilder.Entity<StockRequestItem>(entity =>
        {
            entity.HasKey(e => e.ItemId).HasName("PRIMARY");

            entity.ToTable("stock_request_items");

            entity.HasIndex(e => e.IngredientId, "ingredient_id");

            entity.HasIndex(e => e.RequestId, "request_id");

            entity.Property(e => e.ItemId)
                .HasColumnType("int(11)")
                .HasColumnName("item_id");
            entity.Property(e => e.IngredientId)
                .HasColumnType("int(11)")
                .HasColumnName("ingredient_id");
            entity.Property(e => e.Quantity)
                .HasPrecision(10, 2)
                .HasColumnName("quantity");
            entity.Property(e => e.RequestId)
                .HasColumnType("int(11)")
                .HasColumnName("request_id");

            entity.HasOne(d => d.Ingredient).WithMany(p => p.StockRequestItems)
                .HasForeignKey(d => d.IngredientId)
                .HasConstraintName("stock_request_items_ibfk_2");

            entity.HasOne(d => d.Request).WithMany(p => p.StockRequestItems)
                .HasForeignKey(d => d.RequestId)
                .HasConstraintName("stock_request_items_ibfk_1");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}