// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class Branch
{
    public int BranchId { get; set; }

    public string BranchName { get; set; }

    public string Province { get; set; }

    public string District { get; set; }

    public string SubDistrict { get; set; }

    public string PostalCode { get; set; }

    public string AddressDetail { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public bool? IsUsed { get; set; }

    public virtual ICollection<CounterStock> CounterStocks { get; set; } = new List<CounterStock>();

    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<Shift> Shifts { get; set; } = new List<Shift>();

    public virtual ICollection<StockItem> StockItems { get; set; } = new List<StockItem>();

    public virtual ICollection<StockRequest> StockRequests { get; set; } = new List<StockRequest>();
}