// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class CounterStock
{
    public int CounterStockId { get; set; }

    public int BranchId { get; set; }

    public int IngredientId { get; set; }

    public int Quantity { get; set; }

    public DateTime? LastUpdated { get; set; }

    public virtual Branch Branch { get; set; }

    public virtual Ingredient Ingredient { get; set; }
}