// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class Coupon
{
    public int CouponId { get; set; }

    public string Code { get; set; }

    public string Description { get; set; }

    public string DiscountType { get; set; }

    public decimal? DiscountValue { get; set; }

    public decimal? MinimumPurchase { get; set; }

    public int? MinimumCount { get; set; }

    public DateTime? ExpiryDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public bool? IsUsed { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public virtual ICollection<CustomerCoupon> CustomerCoupons { get; set; } = new List<CustomerCoupon>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}