// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class CustomerPoint
{
    public int CustomerId { get; set; }

    public int? TotalPoints { get; set; }

    public DateTime? LastUpdated { get; set; }

    public virtual Customer Customer { get; set; }
}