// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class CustomerCoupon
{
    public int CustomerId { get; set; }

    public int CouponId { get; set; }

    public bool? IsUsed { get; set; }

    public DateTime? AssignedDate { get; set; }

    public DateTime? UsedDate { get; set; }

    public virtual Coupon Coupon { get; set; }

    public virtual Customer Customer { get; set; }
}