// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class Customer
{
    public int CustomerId { get; set; }

    public string Fullname { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public DateOnly? Birthdate { get; set; }

    public string Password { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public bool? IsUsed { get; set; }

    public virtual ICollection<CustomerCoupon> CustomerCoupons { get; set; } = new List<CustomerCoupon>();

    public virtual CustomerPoint CustomerPoint { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<Referral> ReferralReferreds { get; set; } = new List<Referral>();

    public virtual ICollection<Referral> ReferralReferrers { get; set; } = new List<Referral>();
}