// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class Employee
{
    public int EmployeeId { get; set; }

    public int? BranchId { get; set; }

    public int? RoleId { get; set; }

    public string Fullname { get; set; }

    public string PhoneNumber { get; set; }

    public string PasswordHash { get; set; }

    public DateTime? HireDate { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public bool? IsUsed { get; set; }

    public string Image { get; set; }

    public string Email { get; set; }

    public virtual ICollection<AttendanceLog> AttendanceLogs { get; set; } = new List<AttendanceLog>();

    public virtual Branch Branch { get; set; }

    public virtual ICollection<EmployeeShift> EmployeeShifts { get; set; } = new List<EmployeeShift>();

    public virtual Role Role { get; set; }

    public virtual ICollection<StockRequest> StockRequests { get; set; } = new List<StockRequest>();
}