// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class EmployeeShift
{
    public int Esid { get; set; }

    public int? EmployeeId { get; set; }

    public int? ShiftId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? UpdateDate { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public bool? IsUsed { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual Shift Shift { get; set; }
}