// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class Ingredient
{
    public int IngredientId { get; set; }

    public string Name { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public bool? IsUsed { get; set; }

    public string Unit { get; set; }

    public virtual ICollection<CounterStock> CounterStocks { get; set; } = new List<CounterStock>();

    public virtual ICollection<MenuRecipe> MenuRecipes { get; set; } = new List<MenuRecipe>();

    public virtual ICollection<StockItem> StockItems { get; set; } = new List<StockItem>();

    public virtual ICollection<StockRequestItem> StockRequestItems { get; set; } = new List<StockRequestItem>();
}