// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class Menu
{
    public int MenuId { get; set; }

    public string Name { get; set; }

    public decimal? Price { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public bool? IsUsed { get; set; }

    public int? CategoryId { get; set; }

    public string Image { get; set; }

    public virtual MenuCategory Category { get; set; }

    public virtual ICollection<MenuRecipe> MenuRecipes { get; set; } = new List<MenuRecipe>();

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();
}