// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class MenuRecipe
{
    public int RecipeId { get; set; }

    public int? MenuId { get; set; }

    public int? IngredientId { get; set; }

    public decimal? Quantity { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public virtual Ingredient Ingredient { get; set; }

    public virtual Menu Menu { get; set; }
}