// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class Order
{
    public int OrderId { get; set; }

    public int? CustomerId { get; set; }

    public int? BranchId { get; set; }

    public DateTime? OrderTime { get; set; }

    public string Channel { get; set; }

    public string PaymentMethod { get; set; }

    public string PickupMethod { get; set; }

    public decimal? TotalAmount { get; set; }

    public decimal? DiscountAmount { get; set; }

    public decimal? FinalAmount { get; set; }

    public int? CouponId { get; set; }

    public int? PointsEarned { get; set; }

    public int? PointsUsed { get; set; }

    public string Status { get; set; }

    public DateTime? PickupTime { get; set; }

    public string DeliveryStatus { get; set; }

    public virtual Branch Branch { get; set; }

    public virtual Coupon Coupon { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();
}