// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class Referral
{
    public int ReferralId { get; set; }

    public int? ReferrerId { get; set; }

    public int? ReferredId { get; set; }

    public DateTime? ReferredDate { get; set; }

    public bool? RewardGiven { get; set; }

    public virtual Customer Referred { get; set; }

    public virtual Customer Referrer { get; set; }
}