// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class Refreshtoken
{
    public int Rfid { get; set; }

    public int UserId { get; set; }

    public string JwtTokenId { get; set; }

    public string RefreshToken { get; set; }

    public bool IsValid { get; set; }

    public DateTime ExpiresAt { get; set; }
}