// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class StockRequest
{
    public int RequestId { get; set; } 

    public int? EmployeeId { get; set; }

    public int? BranchId { get; set; }

    public DateTime? RequestDate { get; set; }

    public string Status { get; set; }

    public string ApprovedBy { get; set; }

    public DateTime? ApprovedDate { get; set; }

    public string RequestType { get; set; }

    public virtual Branch Branch { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual ICollection<StockRequestItem> StockRequestItems { get; set; } = new List<StockRequestItem>();
}