// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace Domain.Entities;

public partial class StockRequestItem
{
    public int ItemId { get; set; }

    public int? RequestId { get; set; }

    public int? IngredientId { get; set; }

    public decimal? Quantity { get; set; }

    public virtual Ingredient Ingredient { get; set; }

    public virtual StockRequest Request { get; set; }
}